parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symfony
    database_user: startkit
    database_password: 1start-3-kit7
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: f373aaf6b29910fedb0c8c353b695b1098
    database_path: null